Valid postgres replication slot
transferwise/pipelinewise pull request #530
Opened 2020-09-16 17:39 UTC by hgrsd

## Problem

When using logical replication from a Postgres tap, Pipelinewise generates the name of the Postgres replication slot used from a combination of prefix, database name, and tap name. This does not work if any of the constituent parts contain characters that are not valid in Postgres replication slot names, or if the full generated name is more than 64 characters long.

## Proposed changes

Replace invalid characters with an underscore and truncate the generated name at 64 characters. See https://github.com/transferwise/pipelinewise/issues/529.

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [X] Description above provides context of the change
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

2020-09-17 13:34 UTC, koszti requested changes
...

2020-09-18 17:01 UTC, hgrsd commented
Hmm, good questions. Thinking this through (without a lot of familiarity with Pipelinewise!), my view is probably as follows.

- I don't think we can call external functions from a JSON schema
- Adding a maximum length to fields in the JSON schema comes with its own problems. Three concerns come to mind: 
  - As you say, if we decide a limit on the database name length we might be excluding databases with long names even though we'd be able to generate a replication slot name by truncating the name.
  - We might be invalidating existing replication slots that people are currently using because either their database or tap id might be longer than the limit we decide, even though in _combination_  (and in combination with the prefix) the generated name would not amount to more than 64 characters.
   - We'd be applying a limit that is specific to one feature of Postgres to users who do not use the logical replication method at all

Perhaps the "right" solution is in fact to be less smart:
- we replace invalid characters in the database name by underscores (because database names can be awkward to change, especially in production environments)
- we do _not_ replace invalid characters in the tap id: we can add the valid characters to the Postgres tap documentation; and if the user makes a mistake the tap id is easy to change in the yaml file with zero repercussions
- we do _not_ truncate to 64 characters: again, we can add this limit to the documentation, and if the user has a combination of dbname & tap id that is > 64 characters, they will have to decide how to deal with it, most likely by shortening their chosen tap id

This limits the interference with the user's data to a minimum, ensures that we don't need any database renames (which to me would be the key benifit of this PR), is backwards compatible (because we know that there can be no invalid replication slots that are currently being used), and means that any issue can be resolved by the user in their yaml configuration. 

What do you think?

2020-09-21 08:33 UTC, koszti commented
Related PR for ppw-tap-postgres: https://github.com/transferwise/pipelinewise-tap-postgres/pull/63. We'll need to release a new version to PyPI and bump the postgres tap [here](https://github.com/transferwise/pipelinewise/blob/master/singer-connectors/tap-postgres/requirements.txt).

2020-09-21 08:53 UTC, hgrsd commented
Thanks @koszti. How do you and @Samira-El feel about the approach outlined above? We could make it slightly smarter by truncating _only the database name_ if the total length of the generated replication slot name is more than 64 characters. That way the user will retain the ability to prevent name collisions because we make sure not to interfere with their chosen tap id.

2020-09-21 10:37 UTC, koszti commented
There is no perfect solution.

I'd replace the invalid characters both in dbname and tap_id to keep the behaviours in sync.

And I wouldn't truncate the generated slot name to 64 characters. If it's too long then it will fail at runtime. We can't check the generated length by jsonschemas at import time but I think that's still fine. Having too long replication slot name is a very rare situation and we wouldn't break anything. If it's too then we need to shorten the tap_id.

@Samira-El what do you think?

2020-09-21 11:09 UTC, Samira-El commented
Hey all,

Thanks btw for the PR!

According to the section **_26.2.6.1. Querying And Manipulating Replication Slots_** in the [PG doc](https://www.postgresql.org/docs/current/warm-standby.html#STREAMING-REPLICATION-SLOTS), the only restriction on the slot name is it should only contain lower-case letters, numbers, and the underscore character.

So having mentioned that, I agree with Peter, I'd replace the invalid chars in the slot name.
The PG doc doesn't mention any restriction on the slot length, or maybe I've missed it somewhere, so I wouldn't enforce the 64 chars limit.

2020-09-21 11:17 UTC, hgrsd commented
Thank you both. I've updated this PR and the PR in the postgres tap repo so that we no longer truncate the name to 64 chars. Thanks for helping figure out the best approach to this!

2020-09-21 12:15 UTC, koszti commented
I merged https://github.com/transferwise/pipelinewise-tap-postgres/pull/63 but there are a couple of other pending PRs in tap-postgres: https://github.com/transferwise/pipelinewise-tap-postgres/pull/62 and https://github.com/transferwise/pipelinewise-tap-postgres/pull/64

We need to decide if we want to put all of them into next tap-postgres release or it's better to create a new one only for this PR.

2020-09-21 12:22 UTC, hgrsd commented
> We need to decide if we want to put all of them into next tap-postgres release or it's better to release now onto PyPI so we have a new version only for this PR.

I'm unfamiliar with the release strategy for this project so not sure if I have a very useful point of view, apart from the fact that for us it'd be great if this could be released relatively soon. It'll save us from having to rename a database 😁 .

Do ping me if you need any action from me on this PR.

2020-09-21 12:52 UTC, koszti commented
@hgrsd tap-postgres 1.6.4 is now available on PyPI. Can you please bump the connecter [here](https://github.com/transferwise/pipelinewise/blob/master/singer-connectors/tap-postgres/requirements.txt) ?

2020-09-21 12:58 UTC, koszti approved these changes

2020-09-21 12:58 UTC, merged