Update documentation with the new github tap functionality
transferwise/pipelinewise pull request #755
Opened 2021-07-21 20:08 UTC by rafael-lima-tw

## Problem

Updating documentation with new fields

## Proposed changes

Public doc changes only

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] Description above provides context of the change
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

2021-07-22 08:37 UTC, diegofurtados approved these changes

2021-07-23 12:51 UTC, koszti requested changes

2021-07-23 12:51 UTC, koszti commented on docs/connectors/taps/github.rst
> +      organization: "transferwise"              # The organization you want to extract the data from
can you please change it to something generic open source and not company specific? Maybe `apache` or some other large OS repos is a better choice

2021-07-23 13:17 UTC, koszti approved these changes

2021-07-23 13:22 UTC, merged