Ee 000 update tap GitHub schema
transferwise/pipelinewise pull request #756
Opened 2021-07-23 14:13 UTC by rafael-lima-tw

## Problem

We need to guarantee that the tap github contract is being broken

## Proposed changes

Add json schema validation for tap-github

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] Description above provides context of the change
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

2021-07-26 09:38 UTC, diegofurtados approved these changes

2021-07-26 11:19 UTC, Samira-El requested changes
Left few comments.

Can you also please add unit tests for this validation, they should be located [here](https://github.com/transferwise/pipelinewise/blob/master/tests/units/cli/test_cli_utils.py)

2021-07-26 11:19 UTC, Samira-El commented on pipelinewise/cli/schemas/tap.json
> +            "max_rate_limit_wait_seconds": {
Can you set a sane min and max for this parameter?

2021-07-26 11:19 UTC, Samira-El commented on pipelinewise/cli/schemas/tap.json
> +          "properties": {
`start_date` is missing, it's also a required property

2021-07-26 11:19 UTC, Samira-El commented on pipelinewise/cli/schemas/tap.json
> +        "db_conn": {
Can you add conditions so that either `repository` or `organization` is present?

2021-07-29 13:11 UTC, beveradb submitted a review, later dismissed

2021-07-30 12:04 UTC, beveradb submitted a review, later dismissed

2021-08-02 10:50 UTC, diegofurtados approved these changes

2021-08-02 11:26 UTC, Samira-El commented on pipelinewise/cli/schemas/tap.json
> +              ]
I don't this block is doing anything tbh, I ran it against some scenarios and it passed when it should have failed.
Better to remove it than keep it.

2021-08-02 12:10 UTC, Samira-El approved these changes

2021-08-02 13:08 UTC, merged